id: P006753
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:04.737385
source_metadata:
  id: bdr:W1KG22207
  title: ལྷ་ས་མན་རྩིས་ཁང་གི་གདན་རབ་དྲི་མེད་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  volumes:
    734c20c116ed4923bc63f7a21e16bd64:
      image_group_id: I1KG22255
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
