id: I39EB6896
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:32:33+00:00'
last_modified: '2022-06-08T06:36:53.078945+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22207
  title: ལྷ་ས་མན་རྩིས་ཁང་གི་གདན་རབ་དྲི་མེད་ཤེལ་གྱི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    DF55:
      image_group_id: I1KG22255
      title: ''
      total_pages: 268
      order: 1
      base_file: DF55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
